networks:
  redis:

services:
  redis:
    image: redis:7.4.5
    container_name: redis
    networks:
      - redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: mysecretpassword
    ports:
      - "6379:6379"
