networks:
  http:

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - http
    restart: unless-stopped
    ports:
      - "8080:80"   # HTTP
    volumes:
      - "../static:/usr/share/nginx/html:ro"  # Serve static files